### ISSUE TITLE
Use ray instead of multiprocess in `empirical_line`

### ISSUE THREAD

**Issue by ashiklom** [isofit/isofit#161]
I ran into some very strange interaction between `ray` and `multiprocess` while trying to run the `empirical_line` function (it tried to spawn multiple Python processes, each trying to be a ray master that re-started the full Isofit workflow. It was crazy! No idea what happened...). Regardless, since we seem to have committed to `ray` anyway (which is fine! I've grown to really like it!), I wonder if it would make sense to migrate the `empirical_line` code to use `ray` anyway. Here's what the [diff looks like](https://github.com/ashiklom/isofit/commit/4aa5cdc8faf305fee1e3cca55c0618f3d31e8fc9).

I tested this locally and it seems to work pretty well. Let me know if this is acceptable and I can open a PR.

**Comment by pgbrodrick** [comment]
Hi Alexey,

Absolutely no problem to make this switch - the only reason it hasn't been done is that I wrote the parallelism of empirical_line just before the ray switch, and because the relative additional benefit of ray in the empirical_line is low (given the efficiency and stability with the direct binary dumps I used) - but that's just why it hasn't been reached yet, no reason not to do it.

Looking at the diff you provide, I assume the the ic (must be a config?) would be replaced with direct input arguments, but then it generally looks good.  Please also be sure to add an explicit ray.shutdown() call at the end of the function.

If you're feeling particularly inspired, I also haven't gotten to parallelizing the segmentation and extraction codes yet, though it could certainly be done (tad bit tricky because of the chunking involved, as with the empirical line, but it would work).  Just tossing that out there in case you're itching for more parallelization work :-).

**Comment by ashiklom** [comment]
Great! I'll try to put together a PR in the next few days.
